# Generated by Django 5.1.3 on 2024-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('live', 'Live'), ('finished', 'Finished'), ('upcoming', 'Upcoming')], max_length=10)),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
