# Generated by Django 5.1.3 on 2025-01-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_followecount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FolloweCount',
            new_name='FollowerCount',
        ),
    ]
