# Generated by Django 5.1.3 on 2024-11-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_vote_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(blank=True, choices=[('team_A', 'Team A'), ('team_B', 'Team B')], default=None, max_length=50),
        ),
    ]
