# Generated by Django 5.1.3 on 2024-12-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_tournament_name'),
        ('polls', '0007_alter_vote_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='team_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_A', to='matches.team'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='team_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_B', to='matches.team'),
        ),
    ]
