# Generated by Django 5.1.3 on 2024-11-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrooms',
            name='is_privated',
        ),
    ]
