# Generated by Django 5.1.3 on 2024-12-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.TextField(default='https://img.freepik.com/free-vector/blue-circle-with-white-user_78370-4707.jpg?ga=GA1.1.2067715509.1733308090&semt=ais_hybrid'),
        ),
    ]
